//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTokenPolicy) DeepCopyInto(out *ClusterTokenPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTokenPolicy.
func (in *ClusterTokenPolicy) DeepCopy() *ClusterTokenPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterTokenPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTokenPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTokenPolicyList) DeepCopyInto(out *ClusterTokenPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTokenPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTokenPolicyList.
func (in *ClusterTokenPolicyList) DeepCopy() *ClusterTokenPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterTokenPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTokenPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTokenPolicySpec) DeepCopyInto(out *ClusterTokenPolicySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelPermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultCredentialRef != nil {
		in, out := &in.DefaultCredentialRef, &out.DefaultCredentialRef
		*out = new(CredentialReference)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayIntegration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTokenPolicySpec.
func (in *ClusterTokenPolicySpec) DeepCopy() *ClusterTokenPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterTokenPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTokenPolicyStatus) DeepCopyInto(out *ClusterTokenPolicyStatus) {
	*out = *in
	if in.AppliedNamespaces != nil {
		in, out := &in.AppliedNamespaces, &out.AppliedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTokenPolicyStatus.
func (in *ClusterTokenPolicyStatus) DeepCopy() *ClusterTokenPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterTokenPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialInjection) DeepCopyInto(out *CredentialInjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialInjection.
func (in *CredentialInjection) DeepCopy() *CredentialInjection {
	if in == nil {
		return nil
	}
	out := new(CredentialInjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialReference) DeepCopyInto(out *CredentialReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialReference.
func (in *CredentialReference) DeepCopy() *CredentialReference {
	if in == nil {
		return nil
	}
	out := new(CredentialReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveModel) DeepCopyInto(out *EffectiveModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveModel.
func (in *EffectiveModel) DeepCopy() *EffectiveModel {
	if in == nil {
		return nil
	}
	out := new(EffectiveModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayIntegration) DeepCopyInto(out *GatewayIntegration) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(GatewayTargetRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayIntegration.
func (in *GatewayIntegration) DeepCopy() *GatewayIntegration {
	if in == nil {
		return nil
	}
	out := new(GatewayIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTargetRef) DeepCopyInto(out *GatewayTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTargetRef.
func (in *GatewayTargetRef) DeepCopy() *GatewayTargetRef {
	if in == nil {
		return nil
	}
	out := new(GatewayTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaim) DeepCopyInto(out *ModelClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaim.
func (in *ModelClaim) DeepCopy() *ModelClaim {
	if in == nil {
		return nil
	}
	out := new(ModelClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimList) DeepCopyInto(out *ModelClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimList.
func (in *ModelClaimList) DeepCopy() *ModelClaimList {
	if in == nil {
		return nil
	}
	out := new(ModelClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimSpec) DeepCopyInto(out *ModelClaimSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimSpec.
func (in *ModelClaimSpec) DeepCopy() *ModelClaimSpec {
	if in == nil {
		return nil
	}
	out := new(ModelClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimStatus) DeepCopyInto(out *ModelClaimStatus) {
	*out = *in
	if in.ResolvedModels != nil {
		in, out := &in.ResolvedModels, &out.ResolvedModels
		*out = make([]EffectiveModel, len(*in))
		copy(*out, *in)
	}
	if in.BoundCredentials != nil {
		in, out := &in.BoundCredentials, &out.BoundCredentials
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimStatus.
func (in *ModelClaimStatus) DeepCopy() *ModelClaimStatus {
	if in == nil {
		return nil
	}
	out := new(ModelClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredential) DeepCopyInto(out *ModelCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredential.
func (in *ModelCredential) DeepCopy() *ModelCredential {
	if in == nil {
		return nil
	}
	out := new(ModelCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredentialList) DeepCopyInto(out *ModelCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredentialList.
func (in *ModelCredentialList) DeepCopy() *ModelCredentialList {
	if in == nil {
		return nil
	}
	out := new(ModelCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredentialSpec) DeepCopyInto(out *ModelCredentialSpec) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SecretRef = in.SecretRef
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Injection != nil {
		in, out := &in.Injection, &out.Injection
		*out = new(CredentialInjection)
		**out = **in
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredentialSpec.
func (in *ModelCredentialSpec) DeepCopy() *ModelCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredentialStatus) DeepCopyInto(out *ModelCredentialStatus) {
	*out = *in
	if in.SyncedNamespaces != nil {
		in, out := &in.SyncedNamespaces, &out.SyncedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReferencingPolicies != nil {
		in, out := &in.ReferencingPolicies, &out.ReferencingPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Allocated != nil {
		in, out := &in.Allocated, &out.Allocated
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredentialStatus.
func (in *ModelCredentialStatus) DeepCopy() *ModelCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(ModelCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPermission) DeepCopyInto(out *ModelPermission) {
	*out = *in
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(CredentialReference)
		**out = **in
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPermission.
func (in *ModelPermission) DeepCopy() *ModelPermission {
	if in == nil {
		return nil
	}
	out := new(ModelPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRequest) DeepCopyInto(out *ModelRequest) {
	*out = *in
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(CredentialReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRequest.
func (in *ModelRequest) DeepCopy() *ModelRequest {
	if in == nil {
		return nil
	}
	out := new(ModelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenPolicy) DeepCopyInto(out *TokenPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenPolicy.
func (in *TokenPolicy) DeepCopy() *TokenPolicy {
	if in == nil {
		return nil
	}
	out := new(TokenPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenPolicyList) DeepCopyInto(out *TokenPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TokenPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenPolicyList.
func (in *TokenPolicyList) DeepCopy() *TokenPolicyList {
	if in == nil {
		return nil
	}
	out := new(TokenPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenPolicySpec) DeepCopyInto(out *TokenPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(WorkloadSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelPermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayIntegration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenPolicySpec.
func (in *TokenPolicySpec) DeepCopy() *TokenPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TokenPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenPolicyStatus) DeepCopyInto(out *TokenPolicyStatus) {
	*out = *in
	if in.EffectiveModels != nil {
		in, out := &in.EffectiveModels, &out.EffectiveModels
		*out = make([]EffectiveModel, len(*in))
		copy(*out, *in)
	}
	if in.EffectiveQuota != nil {
		in, out := &in.EffectiveQuota, &out.EffectiveQuota
		*out = new(TokenQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(UsageStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BoundCredentials != nil {
		in, out := &in.BoundCredentials, &out.BoundCredentials
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenPolicyStatus.
func (in *TokenPolicyStatus) DeepCopy() *TokenPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TokenPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenQuota) DeepCopyInto(out *TokenQuota) {
	*out = *in
	if in.TokensPerMinute != nil {
		in, out := &in.TokensPerMinute, &out.TokensPerMinute
		*out = new(int64)
		**out = **in
	}
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int64)
		**out = **in
	}
	if in.TokensPerDay != nil {
		in, out := &in.TokensPerDay, &out.TokensPerDay
		*out = new(int64)
		**out = **in
	}
	if in.TokensPerMonth != nil {
		in, out := &in.TokensPerMonth, &out.TokensPerMonth
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenQuota.
func (in *TokenQuota) DeepCopy() *TokenQuota {
	if in == nil {
		return nil
	}
	out := new(TokenQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageStatus) DeepCopyInto(out *UsageStatus) {
	*out = *in
	if in.WindowStart != nil {
		in, out := &in.WindowStart, &out.WindowStart
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageStatus.
func (in *UsageStatus) DeepCopy() *UsageStatus {
	if in == nil {
		return nil
	}
	out := new(UsageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
